#!/usr/bin/env bash
# Re-downloads the latin subset of Italiana + Jost into the theme and
# regenerates assets/fonts/fonts.css. Run only when the typefaces change.
#
# Jost is served by Google as a single variable font covering 100-900, so
# asking for four weights returns four byte-identical files. This keeps one and
# declares it with a `font-weight: 100 900` range. Italiana has one weight and
# no bold; headings set in it must stay at 400 or the browser fakes it.
set -euo pipefail

cd "$(dirname "$0")/../theme/amir-al-afia/assets/fonts"
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"

curl -s -A "$UA" \
	"https://fonts.googleapis.com/css2?family=Italiana&family=Jost:wght@400;500;600;700&display=swap" \
	-o gf.css

python - <<'PY'
import hashlib
import re
import urllib.request
from pathlib import Path

RANGE = (
    "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, "
    "U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, "
    "U+2212, U+2215, U+FEFF, U+FFFD"
)

css = Path('gf.css').read_text(encoding='utf-8')
blocks = re.findall(r"/\*\s*([\w\[\]-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)

# family -> {digest: (weight, bytes)}
families: dict[str, dict[str, tuple[str, bytes]]] = {}

for subset, block in blocks:
    if subset != 'latin':
        continue
    family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
    url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
    data = urllib.request.urlopen(url).read()
    digest = hashlib.md5(data).hexdigest()
    families.setdefault(family, {}).setdefault(digest, (weight, data))

faces = []
for family, variants in families.items():
    slug = family.lower().replace(' ', '-')
    if len(variants) == 1:
        # One file for every requested weight: a variable font.
        (weight, data), = variants.values()
        name = f'{slug}-variable.woff2' if len(families[family]) == 1 and family == 'Jost' else f'{slug}-{weight}.woff2'
        Path(name).write_bytes(data)
        is_variable = name.endswith('-variable.woff2')
        src = (
            f"url('{name}') format('woff2-variations'), url('{name}') format('woff2')"
            if is_variable else f"url('{name}') format('woff2')"
        )
        faces.append((family, '100 900' if is_variable else weight, src))
        print(f'  {name:<24} {len(data) // 1024} KB'
              + ('  (variable, covers every weight)' if is_variable else ''))
    else:
        for weight, data in sorted(variants.values(), key=lambda v: v[0]):
            name = f'{slug}-{weight}.woff2'
            Path(name).write_bytes(data)
            faces.append((family, weight, f"url('{name}') format('woff2')"))
            print(f'  {name:<24} {len(data) // 1024} KB')

out = [
    "/* Self-hosted Italiana + Jost (latin subset) - generated by tools/fetch-fonts.sh"
    "\n *"
    "\n * Jost ships from Google as a single variable font covering 100-900, so one"
    "\n * 26 KB file replaces the four static weights the site uses. Italiana has a"
    "\n * single weight by design - there is no bold, and asking for one only gets a"
    "\n * synthesised smear, so headings set in it must stay at 400."
    "\n */\n"
]
for family, weight, src in faces:
    out.append(
        f"\n@font-face {{\n\tfont-family: '{family}';\n\tfont-style: normal;\n"
        f"\tfont-weight: {weight};\n\tfont-display: swap;\n\tsrc: {src};\n"
        f"\tunicode-range: {RANGE};\n}}\n"
    )

Path('fonts.css').write_text(''.join(out), encoding='utf-8')
PY

rm -f gf.css
