#!/usr/bin/env bash
# Re-downloads the latin subset of Barlow + Barlow Condensed into the theme
# and regenerates assets/fonts/fonts.css. Run only when the weight set changes.
set -euo pipefail
cd "$(dirname "$0")/../theme/amir-al-afia/assets/fonts"
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
curl -s -A "$UA" "https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@800;900&family=Barlow:wght@400;500;600;700&display=swap" -o gf.css
python - <<'PY'
import re, urllib.request
css = open('gf.css', encoding='utf-8').read()
blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
out = []
for subset, block in blocks:
    if subset != 'latin':
        continue
    fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    wt  = re.search(r"font-weight:\s*(\d+)", block).group(1)
    url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
    slug = fam.lower().replace(' ', '-') + '-' + wt + '.woff2'
    urllib.request.urlretrieve(url, slug)
    out.append(
        "@font-face{font-family:'%s';font-style:normal;font-weight:%s;font-display:swap;"
        "src:url('%s') format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,"
        "U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,"
        "U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;}" % (fam, wt, slug)
    )
    print('fetched', slug)
open('fonts.css', 'w', encoding='utf-8').write(
    "/* Self-hosted Barlow + Barlow Condensed (latin subset) - generated by tools/fetch-fonts.sh */\n"
    + "\n".join(out) + "\n"
)
PY
rm -f gf.css
